from app.database.connection import Base
from app.models.models import (
    User,
    Artist,
    Album,
    Track,
    ListeningEvent,
    TrackEmbedding,
    TrackCoordinate,
    TrackCluster,
    ClusterLabel,
    UserEra,
    ClusteringRun,
    ClusteringAssignment,
    TrackClusterCoordinate,
    ClusterCentroid,
    ClusterArchetype,
    CommunityArchetypeAssignment,
    ClusterLabelArchive,
    TrackVibeCoordinate,
)