"""add canonical_name to cluster_labels

Revision ID: 10d5a4524dd6
Revises: fdd488adbcd1
Create Date: 2026-06-09 00:43:05.513953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d5a4524dd6'
down_revision: Union[str, Sequence[str], None] = 'fdd488adbcd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_labels', sa.Column('canonical_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_labels', 'canonical_name')
    # ### end Alembic commands ###
