"""add_source_run_id_and_cluster_layer_to_cluster_labels

Revision ID: 465ceeec1e2f
Revises: 4c9c1b7cde2b
Create Date: 2026-06-14 17:38:27.288395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465ceeec1e2f'
down_revision: Union[str, Sequence[str], None] = '4c9c1b7cde2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('cluster_labels', sa.Column('source_run_id', sa.Integer(), nullable=True, server_default='18'))
    op.add_column('cluster_labels', sa.Column('cluster_layer', sa.String(), nullable=True, server_default='scene'))
    op.add_column('cluster_labels_archive', sa.Column('source_run_id', sa.Integer(), nullable=True, server_default='18'))
    op.add_column('cluster_labels_archive', sa.Column('cluster_layer', sa.String(), nullable=True, server_default='scene'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_labels_archive', 'cluster_layer')
    op.drop_column('cluster_labels_archive', 'source_run_id')
    op.drop_column('cluster_labels', 'cluster_layer')
    op.drop_column('cluster_labels', 'source_run_id')
    # ### end Alembic commands ###
