"""phase20b_fix_user_eras_unique_constraint_era_type

Revision ID: 476868b9ab11
Revises: a67a4d9d1c2e
Create Date: 2026-07-07 22:42:33.739792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476868b9ab11'
down_revision: Union[str, Sequence[str], None] = 'a67a4d9d1c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_eras_user_era_number'), 'user_eras', type_='unique')
    op.create_unique_constraint('uq_user_eras_user_era_type_number', 'user_eras', ['user_id', 'era_type', 'era_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_eras_user_era_type_number', 'user_eras', type_='unique')
    op.create_unique_constraint(op.f('uq_user_eras_user_era_number'), 'user_eras', ['user_id', 'era_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
