"""add_pure_prose_document

Revision ID: 4c9c1b7cde2b
Revises: 041ada278e1f
Create Date: 2026-06-13 16:33:06.362156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9c1b7cde2b'
down_revision: Union[str, Sequence[str], None] = '041ada278e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('pure_prose_document', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'pure_prose_document')
    # ### end Alembic commands ###
