"""vibe_centroids_soft_assignment

Revision ID: 540d3b8f7ca6
Revises: 465ceeec1e2f
Create Date: 2026-06-14 17:51:23.977115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540d3b8f7ca6'
down_revision: Union[str, Sequence[str], None] = '465ceeec1e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vibe_cluster_centroids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('raw_centroid', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    op.add_column('clustering_assignments', sa.Column('assignment_type', sa.String(), nullable=True, server_default='hard'))
    op.add_column('clustering_assignments', sa.Column('soft_cluster_id', sa.Integer(), nullable=True))
    op.add_column('clustering_assignments', sa.Column('soft_similarity', sa.Float(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clustering_assignments', 'soft_similarity')
    op.drop_column('clustering_assignments', 'soft_cluster_id')
    op.drop_column('clustering_assignments', 'assignment_type')
    op.drop_table('vibe_cluster_centroids')
    # ### end Alembic commands ###
