"""fix_cluster_labels_unique_constraint_to_id_layer

Revision ID: 7363dcbd4926
Revises: 540d3b8f7ca6
Create Date: 2026-06-14 18:14:27.677298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7363dcbd4926'
down_revision: Union[str, Sequence[str], None] = '540d3b8f7ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cluster_labels_cluster_id_key'), 'cluster_labels', type_='unique')
    op.create_unique_constraint('uq_cluster_labels_id_layer', 'cluster_labels', ['cluster_id', 'cluster_layer'])
    op.create_unique_constraint('uq_cluster_labels_archive_id_layer', 'cluster_labels_archive', ['cluster_id', 'cluster_layer'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cluster_labels_archive_id_layer', 'cluster_labels_archive', type_='unique')
    op.drop_constraint('uq_cluster_labels_id_layer', 'cluster_labels', type_='unique')
    op.create_unique_constraint(op.f('cluster_labels_cluster_id_key'), 'cluster_labels', ['cluster_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
