"""phase20_extended_history_columns

Revision ID: 943bdd182e63
Revises: c7f1a4b92e03
Create Date: 2026-07-07 19:22:26.039949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943bdd182e63'
down_revision: Union[str, Sequence[str], None] = 'c7f1a4b92e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listening_events', sa.Column('ms_played', sa.Integer(), nullable=True))
    op.add_column('listening_events', sa.Column('spotify_track_uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listening_events', 'spotify_track_uri')
    op.drop_column('listening_events', 'ms_played')
    # ### end Alembic commands ###
