"""phase20b_era_type_two_timeline

Revision ID: a67a4d9d1c2e
Revises: 943bdd182e63
Create Date: 2026-07-07 22:41:08.785706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67a4d9d1c2e'
down_revision: Union[str, Sequence[str], None] = '943bdd182e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('user_eras', sa.Column('era_type', sa.String(), server_default='discovery', nullable=True))
    op.execute("UPDATE user_eras SET era_type = 'discovery' WHERE era_type IS NULL")

    op.add_column('era_labels', sa.Column('era_type', sa.String(), server_default='discovery', nullable=True))
    op.execute("UPDATE era_labels SET era_type = 'discovery' WHERE era_type IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_eras', 'era_type')
    op.drop_column('era_labels', 'era_type')
    # ### end Alembic commands ###
