"""ml2d_audio_features_and_vibe_columns

Revision ID: c06bfccde289
Revises: f7c6d3970e04
Create Date: 2026-06-13 00:04:07.033382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06bfccde289'
down_revision: Union[str, Sequence[str], None] = 'f7c6d3970e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('bpm', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('audio_energy', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('audio_danceability', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('audio_acousticness', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('audio_liveness', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('audio_key', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('getsongbpm_id', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('audio_features_source', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('vibe_document', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('vibe_combined_document', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('vibe_source', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('vibe_generated_at', sa.DateTime(), nullable=True))
    op.add_column('tracks', sa.Column('vibe_edited_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'vibe_edited_at')
    op.drop_column('tracks', 'vibe_generated_at')
    op.drop_column('tracks', 'vibe_source')
    op.drop_column('tracks', 'vibe_combined_document')
    op.drop_column('tracks', 'vibe_document')
    op.drop_column('tracks', 'audio_features_source')
    op.drop_column('tracks', 'getsongbpm_id')
    op.drop_column('tracks', 'audio_key')
    op.drop_column('tracks', 'audio_liveness')
    op.drop_column('tracks', 'audio_acousticness')
    op.drop_column('tracks', 'audio_danceability')
    op.drop_column('tracks', 'audio_energy')
    op.drop_column('tracks', 'bpm')
    # ### end Alembic commands ###
