"""phase15_taxonomy_tables

Revision ID: d152bda7f22c
Revises: c06bfccde289
Create Date: 2026-06-13 15:51:01.782098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd152bda7f22c'
down_revision: Union[str, Sequence[str], None] = 'c06bfccde289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_archetypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archetype_id')
    )
    op.create_table('cluster_centroids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('raw_centroid', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('umap15_centroid', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('map2d_centroid', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    op.create_table('cluster_labels_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cluster_archetype', sa.String(), nullable=True),
    sa.Column('label_version', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_archetype_assignments',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.add_column('cluster_labels', sa.Column('label_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_labels', 'label_version')
    op.drop_table('community_archetype_assignments')
    op.drop_table('cluster_labels_archive')
    op.drop_table('cluster_centroids')
    op.drop_table('cluster_archetypes')
    # ### end Alembic commands ###
