"""ml2b_document_types_and_embeddings_update

Revision ID: f7c6d3970e04
Revises: 6658dea28781
Create Date: 2026-06-12 15:40:29.832326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c6d3970e04'
down_revision: Union[str, Sequence[str], None] = '6658dea28781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add as nullable first to backfill existing rows, then enforce NOT NULL
    op.add_column('track_embeddings', sa.Column('document_type', sa.String(), nullable=True))
    op.execute("UPDATE track_embeddings SET document_type = 'original' WHERE document_type IS NULL")
    op.alter_column('track_embeddings', 'document_type', nullable=False)
    op.drop_constraint('track_embeddings_track_id_key', 'track_embeddings', type_='unique')
    op.create_unique_constraint('uq_track_embeddings_track_doc_type', 'track_embeddings', ['track_id', 'document_type'])
    op.add_column('tracks', sa.Column('scene_document', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('sound_document', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('behavior_document', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'behavior_document')
    op.drop_column('tracks', 'sound_document')
    op.drop_column('tracks', 'scene_document')
    op.drop_constraint('uq_track_embeddings_track_doc_type', 'track_embeddings', type_='unique')
    op.create_unique_constraint(op.f('track_embeddings_track_id_key'), 'track_embeddings', ['track_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('track_embeddings', 'document_type')
    # ### end Alembic commands ###
