/**
 * Spotify Atlas — backend response types.
 *
 * These interfaces mirror the exact JSON shapes returned by the FastAPI
 * backend at http://127.0.0.1:8000 (audited in Phase U0). Field names are
 * kept identical to the API; user-facing renaming (e.g. "communities" instead
 * of "clusters") happens in the UI layer, not here.
 */

/** Rarity tiers derived from a community's total track count. */
export type Rarity =
  | "Extremely Rare"
  | "Rare"
  | "Niche"
  | "Underground"
  | "Core";

// ---------------------------------------------------------------------------
// GET /profile/taste?user_id={id}&time_range={all|6months|30days}
// ---------------------------------------------------------------------------

/**
 * A single music community in the user's taste profile.
 * NOTE: `cluster_id` is an internal id used for routing/lookups only and must
 * never be surfaced in user-facing copy.
 */
export interface Community {
  cluster_id: number;
  /** Personal, culturally-specific display name (e.g. "October's Very Own"). */
  name: string;
  /** Generic/canonical descriptor (e.g. "Toronto R&B & Hip-Hop"). */
  canonical_name: string;
  description: string;
  keywords: string[];
  /** Share of the user's taste, 0–100, rounded to 1 decimal. */
  percentage: number;
  /** Raw weighted listening score backing the percentage. */
  weight: number;
  top_artists: string[];
  rarity: Rarity;
  track_count: number;
  /** Parent archetype name, or null if the community is unassigned. */
  archetype: string | null;
}

/** Response for GET /profile/taste. `communities` is capped at 50, sorted desc by weight. */
export interface TasteProfile {
  user_id: number;
  total_weight: number;
  communities: Community[];
}

/** Allowed `time_range` query values for the taste endpoint. */
export type TasteTimeRange = "all" | "6months" | "30days";

// ---------------------------------------------------------------------------
// GET /profile/summary?user_id={id}
// ---------------------------------------------------------------------------

/**
 * Response for GET /profile/summary.
 * `title` is a short evocative identity name (e.g. "Explorer of Worlds").
 * `summary` is plain prose — no markdown, no bullets, max ~4 sentences.
 * Both are generated by the LLM; the call can take several seconds.
 */
export interface TasteSummary {
  title: string;
  summary: string;
}

// ---------------------------------------------------------------------------
// GET /clusters/archetypes
// ---------------------------------------------------------------------------

/** A community as listed inside an archetype group (lighter than `Community`). */
export interface ArchetypeCommunity {
  cluster_id: number;
  name: string;
  canonical_name: string;
  description: string;
}

/** One archetype group and the communities it contains. */
export interface Archetype {
  name: string;
  cluster_count: number;
  clusters: ArchetypeCommunity[];
}

/** Response for GET /clusters/archetypes, sorted alphabetically by archetype name. */
export interface ArchetypesResponse {
  archetypes: Archetype[];
}

// ---------------------------------------------------------------------------
// GET /clusters/{id}/related
// ---------------------------------------------------------------------------

/** A neighbouring community with a cosine-style similarity score (0–1). */
export interface RelatedCommunity {
  cluster_id: number;
  name: string;
  canonical_name: string;
  similarity: number;
}

/** Response for GET /clusters/{id}/related. */
export interface RelatedResponse {
  cluster_id: number;
  related: RelatedCommunity[];
}

// ---------------------------------------------------------------------------
// GET /clusters/labels
// ---------------------------------------------------------------------------

/** A full label record for a community (used to enrich map data). */
export interface ClusterLabel {
  cluster_id: number;
  name: string;
  canonical_name: string;
  description: string;
  keywords: string[];
  /** Parent archetype name (may be null for unassigned communities). */
  cluster_archetype: string | null;
}

/** Response for GET /clusters/labels. */
export interface LabelsResponse {
  labels: ClusterLabel[];
}

// ---------------------------------------------------------------------------
// GET /clusters/{id}/detail?user_id={id}
// ---------------------------------------------------------------------------

/**
 * A sample track as returned by the detail endpoint.
 * Includes `spotify_id` (absent from the lighter SampleTrack used in map clusters).
 */
export interface SampleTrackDetail {
  name: string;
  artist: string;
  spotify_id: string;
}

/**
 * Full community detail for a single community, hydrated with the requesting
 * user's listening weight. Returned by GET /clusters/{id}/detail?user_id={id}.
 * NOTE: `percentage` is not returned here; compute it from `user_weight /
 * TasteProfile.total_weight * 100` if needed.
 */
export interface CommunityDetail {
  cluster_id: number;
  name: string;
  canonical_name: string;
  description: string;
  keywords: string[];
  /** Parent archetype name, or null if unassigned. */
  archetype: string | null;
  track_count: number;
  /** Up to 5 top artists by listening weight for this user. */
  top_artists: string[];
  /** Representative track samples with Spotify IDs. */
  sample_tracks: SampleTrackDetail[];
  /** Raw weighted listening score for the requesting user. */
  user_weight: number;
}

// ---------------------------------------------------------------------------
// Galaxy map endpoints (used by the atlas map in Phase U6)
// ---------------------------------------------------------------------------

/** A single track plotted on the 2D galaxy map. */
export interface TrackPoint {
  id: number;
  name: string;
  artist: string;
  x: number;
  y: number;
  /** -1 denotes a noise point (no community). */
  cluster_id: number;
  spotify_id: string;
}

/** Response for GET /map. */
export interface MapData {
  total: number;
  points: TrackPoint[];
}

/** A representative track sample shown in cluster/community previews. */
export interface SampleTrack {
  name: string;
  artist: string;
}

/** Aggregated community node for the map, including its centroid position. */
export interface MapCluster {
  cluster_id: number;
  track_count: number;
  centroid_x: number;
  centroid_y: number;
  top_artists: string[];
  sample_tracks: SampleTrack[];
}

/** Response for GET /map/clusters. */
export interface MapClustersResponse {
  clusters: MapCluster[];
}

/**
 * A map cluster enriched with its label fields. Convenience type for the UI
 * after joining /map/clusters with /clusters/labels.
 */
export interface EnrichedMapCluster extends MapCluster {
  name?: string;
  canonical_name?: string;
  description?: string;
  keywords?: string[];
  cluster_archetype?: string | null;
}

// ---------------------------------------------------------------------------
// GET /eras?user_id={id}
// PATCH /eras/{era_id}
// ---------------------------------------------------------------------------

/** A dominant community attached to an era. */
export interface EraDominantCommunity {
  cluster_id: number;
  name: string;
  /** Parent archetype name, or null if unassigned. */
  archetype: string | null;
}

/** User-editable label fields for an era. */
export interface EraLabel {
  title: string | null;
  description: string | null;
  mood: string | null;
  is_named: boolean;
}

/** A single listening era in chronological order. */
export interface Era extends EraLabel {
  era_id: number;
  era_number: number;
  start_date: string;
  end_date: string;
  event_count: number;
  dominant_communities: EraDominantCommunity[];
}

/** Request body for PATCH /eras/{era_id}. */
export interface EraLabelUpdate {
  title?: string;
  description?: string;
  mood?: string;
}

/** Response for PATCH /eras/{era_id}. */
export interface EraPatchResponse {
  era_id: number;
  era_number: number;
  title: string | null;
  description: string | null;
  mood: string | null;
  key_tracks: unknown[];
  edited_at: string | null;
}

/** Ranked artist by raw event count within an era. */
export interface EraArtistVolume {
  name: string;
  event_count: number;
}

/** Ranked artist by TF-IDF-style distinctiveness within an era. */
export interface EraArtistDistinctiveness {
  name: string;
  distinctiveness_score: number;
  era_frequency: number;
}

/** Representative track ranked by era distinctiveness. */
export interface EraRepresentativeTrack {
  name: string;
  artist: string;
  distinctiveness_score: number;
}

/** Aggregated genre/mood tag from track feature documents. */
export interface EraTagCount {
  tag: string;
  count: number;
}

/** Percentage of era events per archetype. */
export interface EraArchetypeBreakdown {
  archetype: string;
  percentage: number;
}

/** Response for GET /eras/{era_id}/depth. */
export interface EraDepth {
  era_id: number;
  era_number: number;
  title: string;
  start_date: string;
  end_date: string;
  event_count: number;
  top_artists_by_volume: EraArtistVolume[];
  top_artists_by_distinctiveness: EraArtistDistinctiveness[];
  representative_tracks: EraRepresentativeTrack[];
  top_genres_moods: EraTagCount[];
  archetype_breakdown: EraArchetypeBreakdown[];
  dominant_communities: EraDominantCommunity[];
}
